name: Test build

# Triggers on pushing to 'main' and 'develop'.
on:
  push:
    branches-ignore:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/actions/checkout#readme
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@3.7.0 --activate
          yarn set version 3.7.0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-packages-${{ hashFiles('**/yarn.lock') }}
          restore-keys: npm-packages-

      - run: yarn install --immutable

      - name: Build
        run: npm run build